CREATE PROCEDURE [ext].[GETUNPRINTEDTRANSIDS]
    @tvp_QueryResultSettings    [crt].[QUERYRESULTSETTINGSTABLETYPE] READONLY,
	@AllTransIds                [crt].[STRINGIDTABLETYPE] READONLY,
	@MinDate                    DATE,
    @MaxDate                    DATE
AS
BEGIN
    SET NOCOUNT ON

	SELECT
	    i.STRINGID
	FROM @AllTransIds i
	WHERE NOT EXISTS (
	    SELECT 1
		FROM [EXT].CONTOSORETAILTRANSACTIONTABLE t
		WHERE i.STRINGID = t.TRANSACTIONID 
	)
END;

GO

GRANT EXECUTE ON [ext].[GETUNPRINTEDTRANSIDS] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[GETUNPRINTEDTRANSIDS] TO [PublishersRole];
GO

select * from [EXT].CONTOSORETAILTRANSACTIONTABLE