DROP PROCEDURE IF EXISTS [ext].[SETTRANSACTIONPRINTED];
GO

CREATE PROCEDURE [ext].[SETTRANSACTIONPRINTED_V2]
	@s_TRANSACTIONID [nvarchar](44),
	@s_STORE [nvarchar](10),
	@bi_CHANNEL [bigint],
	@s_TERMINAL [nvarchar](10),
	@s_DATAAREAID [nvarchar](4),
	@i_ISRECEIPTPRIENTED [int]
AS
BEGIN
    SET NOCOUNT ON
	IF (NOT EXISTS(SELECT * FROM [ext].[CONTOSORETAILTRANSACTIONTABLE] AS T
	 WHERE T.TRANSACTIONID = @s_TRANSACTIONID AND
		   T.STORE = @s_STORE AND
		   T.CHANNEL = @bi_CHANNEL AND
		   T.TERMINAL = @s_TERMINAL AND
		   T.DATAAREAID = @s_DATAAREAID
	 ) )
	BEGIN 
		INSERT INTO [ext].[CONTOSORETAILTRANSACTIONTABLE](TRANSACTIONID, STORE, CHANNEL,TERMINAL,DATAAREAID, ISRECEIPTPRINTED)
		VALUES (@s_TRANSACTIONID, @s_STORE, @bi_CHANNEL,@s_TERMINAL, @s_DATAAREAID, @i_ISRECEIPTPRIENTED) 
	END 
	ELSE 
	BEGIN 
		UPDATE [ext].[CONTOSORETAILTRANSACTIONTABLE] 
		SET ISRECEIPTPRINTED = @i_ISRECEIPTPRIENTED
		WHERE TRANSACTIONID = @s_TRANSACTIONID AND
		   STORE = @s_STORE AND
		  CHANNEL = @bi_CHANNEL AND
		  TERMINAL = @s_TERMINAL AND
		  DATAAREAID = @s_DATAAREAID
	END 
END;
GO

GRANT EXECUTE ON [ext].[SETTRANSACTIONPRINTED] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[SETTRANSACTIONPRINTED] TO [DeployExtensibilityRole];
GO

UPDATE [ext].[CONTOSORETAILTRANSACTIONTABLE] 
		SET ISRECEIPTPRINTED = 1