/**
 * SAMPLE CODE NOTICE
 * 
 * THIS SAMPLE CODE IS MADE AVAILABLE AS IS.  MICROSOFT MAKES NO WARRANTIES, WHETHER EXPRESS OR IMPLIED,
 * OF FITNESS FOR A PARTICULAR PURPOSE, OF ACCURACY OR COMPLETENESS OF RESPONSES, OF RESULTS, OR CONDITIONS OF MERCHANTABILITY.
 * THE ENTIRE RISK OF THE USE OR THE RESULTS FROM THE USE OF THIS SAMPLE CODE REMAINS WITH THE USER.
 * NO TECHNICAL SUPPORT IS PROVIDED.  YOU MAY NOT DISTRIBUTE THIS CODE UNLESS YOU HAVE A LICENSE AGREEMENT WITH MICROSOFT THAT ALLOWS YOU TO DO SO.
 */

 USE AxDbRain

--------------------------------------------------------------------------------------------------------------------
---------------------------------------CONTOSORETAILSTAFFSUGGESTIONS -----------------------------------------------
-------------------------------------------------------------------------------------------------------------------- 
IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILSTAFFSUGGESTIONS]')) IS NOT NULL  
BEGIN
    DROP TABLE [EXT].[CONTOSORETAILSTAFFSUGGESTIONS]
END

CREATE TABLE [ext].CONTOSORETAILSTAFFSUGGESTIONS(
	[SUGGESTIONID] [int] NOT NULL,
	[STOREID] [nvarchar](10) NOT NULL,
	[STAFF] [nvarchar](25) NOT NULL,
	[TERMINALID] [nvarchar](10) NOT NULL,
	[SUGGETION] [nvarchar](255) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[DATELOGGED] [date] NOT NULL,
	[REPLICATIONCOUNTERFROMORIGIN] [int] IDENTITY(1,1) NOT NULL,
	 CONSTRAINT [PK_EXT_CONTOSORETAILSTAFFSUGGESTIONS] PRIMARY KEY CLUSTERED 
(
	[SUGGESTIONID] ASC,
	[STOREID] ASC,
	[TERMINALID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILSTAFFSUGGESTIONS] TO [DataSyncUsersRole];
GO

--------------------------------------------------------------------------------------------------------------------
---------------------------------------ContosoRetailSeatingData ----------------------------------------------------
--------------------------------------------------------------------------------------------------------------------
    --<SUBJOB ID="CONTOSORETAILSEATINGDATA" AXTABLENAME ="CONTOSORETAILSEATINGDATA" TARGETTABLENAME="CONTOSORETAILTABLEDATA" TARGETTABLESCHEMA="EXT">
    --  <SCHEDULEDBYJOBS>
    --    <SCHEDULEDBYJOB>7000</SCHEDULEDBYJOB>
    --  </SCHEDULEDBYJOBS>
    --  <AXFIELDS>
    --    <FIELD NAME="SEATNUMBER" />
    --    <FIELD NAME="CAPACITY" TONAME="NUMBEROFCHAIRS" />
    --    <FIELD NAME="STOREID" />
    --    <FIELD NAME="RECID" />
    --  </AXFIELDS>
    --</SUBJOB>

-----CORRESPONDING SQL CHANNEL SIDE CHANGES FOR THE ABOVE AX SIDE CDX AND TABLE CUSTOMIZATIONS -----------------------

IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILTABLEDATA]')) IS NOT NULL 
BEGIN
   DROP TABLE [EXT].[CONTOSORETAILTABLEDATA]
END

CREATE TABLE [ext].[CONTOSORETAILTABLEDATA](
	[SEATNUMBER] [int] NOT NULL,
	[NUMBEROFCHAIRS] [int] NOT NULL,
	[STORENUMBER] [nvarchar](10) NOT NULL,
	[RECID] [bigint] NOT NULL,
    CONSTRAINT [PK_EXT_CONTOSORETAILTABLEDATA_RECID] PRIMARY KEY CLUSTERED (
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
   CONSTRAINT [PK_EXT_CONTOSORETAILTABLEDATA]  UNIQUE NONCLUSTERED (
	[SEATNUMBER] ASC,
	[STORENUMBER] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILTABLEDATA] TO [DataSyncUsersRole];
GO

--------------------------------------------------------------------------------------------------------------------
---------------------------------------RETAILCHANNELTABLE CUSTOMIZATION---------------------------------------------
--------------------------------------------------------------------------------------------------------------------
    --<SUBJOB ID="RETAILCHANNELTABLE" TARGETTABLENAME="CONTOSORETAILCHANNELTABLE" TARGETTABLESCHEMA="EXT">
    --  <AXFIELDS>
    --    <FIELD NAME="PAYMENT" /> <!-- EXISTING COLUMN WHICH WAS NOT PUSHED TO CHANNEL DB-->
    --    <FIELD NAME="PAYMMODE" /> <!-- EXISTING COLUMN WHICH WAS NOT PUSHED TO CHANNEL DB-->
    --    <FIELD NAME="CONTOSORETAILWALLPOSTMESSAGE" /> <!-- NEW COLUMN FROM THE EXTENDED TABLE -->
    --  </AXFIELDS>
    --</SUBJOB>

-----CORRESPONDING SQL CHANNEL SIDE CHANGES FOR THE ABOVE AX SIDE CDX AND TABLE CUSTOMIZATIONS -----------------------

IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILCHANNELTABLE]')) IS NOT NULL  
BEGIN
   DROP TABLE [EXT].[CONTOSORETAILCHANNELTABLE]
END

CREATE TABLE [ext].[CONTOSORETAILCHANNELTABLE](
	[PAYMENT] [nvarchar](10) NOT NULL,
	[PAYMMODE] [nvarchar](10) NOT NULL,
	[CONTOSORETAILWALLPOSTMESSAGE] [nvarchar](255) NOT NULL,
	[RECID] [bigint] NOT NULL,
	 CONSTRAINT [PK_EXT_CONTOSORETAILCHANNELTABLE_RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILCHANNELTABLE] TO [DataSyncUsersRole];
GO


--------------------------------------------------------------------------------------------------------------------
---------------------------------------RETAILCUSTTABLE CUSTOMIZATION -----------------------------------------------
--------------------------------------------------------------------------------------------------------------------
    --<SUBJOB ID="RETAILCUSTTABLE" TARGETTABLENAME="CONTOSORETAILCUSTTABLE" TARGETTABLESCHEMA="EXT"> <!--THE AXTABLENAME ATTRIBUTE IS NOT USED HERE BECAUSE THIS IS AN ALREADY EXISTING SUBJOB AND WE ARE ONLY CHANGING THE MAPPING. SO NO NEED TO SPECIFY VALUES OF THE ATTRIBUTES THAT WE DONT NEED TO CHANGE -->
    --  <AXFIELDS>
    --    <FIELD NAME="RETURNTAXGROUP_W" /> <!-- EXISTING COLUMN WHICH WAS NOT PUSHED TO CHANNEL DB-->
    --    <FIELD NAME="CONTOSORETAILSSNNUMBER" /> <!-- NEW COLUMN FROM THE EXTENDED TABLE-->
    --  </AXFIELDS>
    --</SUBJOB>

-----CORRESPONDING SQL CHANNEL SIDE CHANGES FOR THE ABOVE AX SIDE CDX AND TABLE CUSTOMIZATIONS -----------------------

IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILCUSTTABLE]')) IS NOT NULL  
BEGIN
  DROP TABLE [EXT].CONTOSORETAILCUSTTABLE
END

CREATE TABLE [ext].[CONTOSORETAILCUSTTABLE](
    [ACCOUNTNUM] [nvarchar](20) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[RETURNTAXGROUP_W] [nvarchar](10) NOT NULL,
	[CONTOSORETAILSSNNUMBER] [nvarchar](11) NOT NULL,
 CONSTRAINT [PK_EXT_CONTOSORETAILCUSTTABLE] PRIMARY KEY CLUSTERED 
(
	[ACCOUNTNUM] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILCUSTTABLE] TO [DataSyncUsersRole];
GO


--------------------------------------------------------------------------------------------------------------------
---------------------------------------RETAILTRANSACTIONTABLE CUSTOMIZATION-----------------------------------------
--------------------------------------------------------------------------------------------------------------------

    --<SUBJOB ID="RETAILTRANSACTIONTABLE" TARGETTABLENAME ="CONTOSORETAILTRANSACTIONTABLE" TARGETTABLESCHEMA="EXT" OVERRIDETARGET="false">
    --  <!--IF YOU NOTICE THERE IS NO MENTION OF THE <SCHEDULEDBYJOBS></SCHEDULEDBYJOBS> BECAUSE THE SUBJOB IS ALREADY PART OF AN UPLOAD JOB. -->
    --  <AXFIELDS>
    --    <!--IF YOU NOTICE THE EXISTING COLUMNS ARE NOT LISTED HERE IN THE <FIELD> TAG, THIS IS BECAUSE THE EISTING FIELDS ARE ALREADY MAPPED MAPPED IN THE MAIN RETAILCDXSEEDDATA RESOURCE FILE WE ONLY ADD THE DELTA HERE. -->
    --    <FIELD NAME="SEATNUMBER" />
    --    <FIELD NAME="SERVERSTAFFID" />
    --  </AXFIELDS>
    --</SUBJOB>

-----CORRESPONDING SQL CHANNEL SIDE CHANGES FOR THE ABOVE AX SIDE CDX AND TABLE CUSTOMIZATIONS -----------------------

IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILTRANSACTIONTABLE]')) IS NOT NULL 
BEGIN
   DROP TABLE [EXT].CONTOSORETAILTRANSACTIONTABLE
END
GO


CREATE TABLE [ext].[CONTOSORETAILTRANSACTIONTABLE](
    [CONTOSORETAILSEATNUMBER] [int] NOT NULL,
	[CONTOSORETAILSERVERSTAFFID] [nvarchar](25) NOT NULL,
	[TRANSACTIONID] [nvarchar](44) NOT NULL,
	[STORE] [nvarchar](10) NOT NULL,
	[CHANNEL] [bigint] NOT NULL,
	[TERMINAL] [nvarchar](10) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_EXT_CONTOSORETAILTRANSACTIONTABLE] PRIMARY KEY CLUSTERED 
(
	[TRANSACTIONID] ASC,
	[STORE] ASC,
	[CHANNEL] ASC,
	[TERMINAL] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILTRANSACTIONTABLE] TO [DataSyncUsersRole];
GO

-- Note:
-- 1) On the channel side if a table is customized we will have TWO TABLES (i.e. the original and the custom table) to hold all the custom and main columns.
-- 2) On AX side if a table is customied - in AOT you will have two "AOT Tables" (i.e. the original and the extension table) but in reality in SQL all the 
--    columns from these two "AOT tables" are saved in the same SINGLE table.
-- 3) CDX upload or pull job works by reading from a primary channel table and all its extension tables, as defined in the CDX extension XML, and writing to a SINGLE AX table.
