USE [AxDB]
GO

/****** Object:  Table [ext].[LOGISTICSADDRESSPARAMETERSExt]    Script Date: 6/21/2023 7:27:42 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [ext].[LOGISTICSADDRESSPARAMETERSExt](
	[RECID] [bigint] NOT NULL,
	[KEY] [int] NULL,
	[DISABLECOUNTYVALIDATION] [int] NOT NULL,
 CONSTRAINT [I_LOGISTICSADDRESSPARAMETERS_RECID] PRIMARY KEY CLUSTERED 
(
	[RECID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


