IF OBJECT_ID(N'[ext].[DELETESTOREDAYHOURS]', N'P') IS NOT NULL
    DROP PROCEDURE [ext].DELETESTOREDAYHOURS
GO

CREATE PROCEDURE [ext].DELETESTOREDAYHOURS
    @bi_Id   BIGINT

AS
BEGIN
    SET NOCOUNT ON

    DELETE FROM  ext.CONTOSORETAILSTOREHOURSTABLE
    WHERE RECID = @bi_Id
END;
GO

GRANT EXECUTE ON [ext].DELETESTOREDAYHOURS TO [UsersRole];
GO

GRANT EXECUTE ON [ext].DELETESTOREDAYHOURS TO [DeployExtensibilityRole];
GO
