IF OBJECT_ID(N'[ext].[INSERTSTOREDAYHOURS]', N'P') IS NOT NULL
    DROP PROCEDURE [ext].INSERTSTOREDAYHOURS
GO

CREATE PROCEDURE [ext].INSERTSTOREDAYHOURS
    @i_Day          INT,
    @i_OpenTime     INT,
    @i_ClosingTime  INT,
    @bi_ChannelId   BIGINT

AS
BEGIN
    SET NOCOUNT ON

    INSERT  ext.CONTOSORETAILSTOREHOURSTABLE(DAY, OPENTIME, CLOSINGTIME, RETAILSTORETABLE) 
    VALUES(@i_Day,  @i_OpenTime, @i_ClosingTime, @bi_ChannelId)
END;
GO

GRANT EXECUTE ON [ext].[INSERTSTOREDAYHOURS] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[INSERTSTOREDAYHOURS] TO [DeployExtensibilityRole];
GO
