IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILTRANSACTIONTABLE]')) IS NOT NULL 
BEGIN
   DROP TABLE [EXT].CONTOSORETAILTRANSACTIONTABLE
END
GO

CREATE TABLE [ext].[CONTOSORETAILTRANSACTIONTABLE](
    [ISRECEIPTPRINTED] [int] NOT NULL,
	[TRANSACTIONID] [nvarchar](44) NOT NULL,
	[STORE] [nvarchar](10) NOT NULL,
	[CHANNEL] [bigint] NOT NULL,
	[TERMINAL] [nvarchar](10) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
 CONSTRAINT [PK_EXT_CONTOSORETAILTRANSACTIONTABLE] PRIMARY KEY CLUSTERED 
(
	[TRANSACTIONID] ASC,
	[STORE] ASC,
	[CHANNEL] ASC,
	[TERMINAL] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILTRANSACTIONTABLE] TO [DataSyncUsersRole];
GO