
IF (SELECT OBJECT_ID('[ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS]')) IS NOT NULL 
BEGIN
   DROP TABLE [EXT].CONTOSORETAILTRANSACTIONPAYMENTTRANS
END
GO

CREATE TABLE [ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS](
	[CHANNEL]             [bigint] NOT NULL,
    [STORE]               [nvarchar](10) NOT NULL,
	[TERMINAL]            [nvarchar](10) NOT NULL,
	[DATAAREAID]          [nvarchar](4) NOT NULL,
    [TRANSACTIONID]       [nvarchar](44) NOT NULL,	
    [LINENUM]             [numeric](32, 16) NOT NULL,
    [BANKTRANSFERCOMMENT] [nvarchar](100) NOT NULL DEFAULT('')
 CONSTRAINT [P_EXT_CONTOSORETAILTRANSACTIONPAYMENTTRANS] PRIMARY KEY CLUSTERED 
(
	[CHANNEL] ASC,
	[STORE] ASC,
	[TERMINAL] ASC,
	[TRANSACTIONID] ASC,
	[LINENUM] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

GRANT INSERT, DELETE, UPDATE, SELECT ON OBJECT::[ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [DataSyncUsersRole];
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [UsersRole]
GO

GRANT SELECT, INSERT, UPDATE, DELETE ON OBJECT::[ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [DeployExtensibilityRole]
GO


-- Create a stored procedure CRT can use to add entries to the custom table.

IF OBJECT_ID(N'[ext].[INSERTCONTOSORETAILTRANSACTIONPAYMENTTRANS]', N'P') IS NOT NULL
    DROP PROCEDURE [ext].[INSERTCONTOSORETAILTRANSACTIONPAYMENTTRANS]
GO

CREATE PROCEDURE [ext].[INSERTCONTOSORETAILTRANSACTIONPAYMENTTRANS]
    @b_CHANNEL    BIGINT,
    @s_STORE      [nvarchar](10),
    @s_TERMINAL   [nvarchar](10),
    @s_DATAAREAID [nvarchar](4),
    @s_TRANSACTIONID [nvarchar](44),
    @n_LINENUM    [numeric](32, 16),
    @s_BANKTRANSFERCOMMENT [nvarchar](100)
AS
BEGIN
    SET NOCOUNT ON

    INSERT INTO
         [ext].[CONTOSORETAILTRANSACTIONPAYMENTTRANS]
        (CHANNEL,STORE,TERMINAL, DATAAREAID, TRANSACTIONID, LINENUM, BANKTRANSFERCOMMENT)
    VALUES
        (@b_CHANNEL, @s_STORE, @s_TERMINAL, @s_DATAAREAID, @s_TRANSACTIONID, @n_LINENUM,  @s_BANKTRANSFERCOMMENT)
END;
GO

GRANT EXECUTE ON [ext].[INSERTCONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[INSERTCONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [DeployExtensibilityRole];
GO

-- Create a stored procedure CRT can use to perform updates.

IF OBJECT_ID(N'[ext].[UPDATECONTOSORETAILTRANSACTIONPAYMENTTRANS]', N'P') IS NOT NULL
    DROP PROCEDURE [ext].[UPDATECONTOSORETAILTRANSACTIONPAYMENTTRANS]
GO

CREATE PROCEDURE [ext].[UPDATECONTOSORETAILTRANSACTIONPAYMENTTRANS]
    @b_CHANNEL    BIGINT,
    @s_STORE      [nvarchar](10),
    @s_TERMINAL   [nvarchar](10),
    @s_DATAAREAID [nvarchar](4),
    @s_TRANSACTIONID [nvarchar](44),
    @n_LINENUM    [numeric](32, 16),
    @s_BANKTRANSFERCOMMENT [nvarchar](100)
AS
BEGIN
    SET NOCOUNT ON
    UPDATE
        ext.[CONTOSORETAILTRANSACTIONPAYMENTTRANS]
    SET
         BankTransferComment = @s_BANKTRANSFERCOMMENT
    WHERE
            CHANNEL  = @b_CHANNEL
		AND STORE    = @s_STORE
		AND TERMINAL = @s_TERMINAL
        AND DATAAREAID = @s_DATAAREAID
		AND TRANSACTIONID = @s_TRANSACTIONID
		AND LINENUM = @n_LINENUM
END;
GO

GRANT EXECUTE ON [ext].[UPDATECONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[UPDATECONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [DeployExtensibilityRole];
GO


IF OBJECT_ID(N'[ext].[DELETECONTOSORETAILTRANSACTIONPAYMENTTRANS]', N'P') IS NOT NULL
    DROP PROCEDURE [ext].[DELETECONTOSORETAILTRANSACTIONPAYMENTTRANS]
GO

CREATE PROCEDURE [ext].[DELETECONTOSORETAILTRANSACTIONPAYMENTTRANS]
    @b_CHANNEL    BIGINT,
    @s_STORE      [nvarchar](10),
    @s_TERMINAL   [nvarchar](10),
    @s_DATAAREAID [nvarchar](4),
    @s_TRANSACTIONID [nvarchar](44),
    @n_LINENUM    [numeric](32, 16),
    @s_BANKTRANSFERCOMMENT [nvarchar](100)
AS
BEGIN
    SET NOCOUNT ON
    DELETE FROM
        ext.[CONTOSORETAILTRANSACTIONPAYMENTTRANS]
    WHERE
            CHANNEL  = @b_CHANNEL
		AND STORE    = @s_STORE
		AND TERMINAL = @s_TERMINAL
        AND DATAAREAID = @s_DATAAREAID
		AND TRANSACTIONID = @s_TRANSACTIONID
		AND LINENUM = @n_LINENUM
END;
GO

GRANT EXECUTE ON [ext].[DELETECONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [UsersRole];
GO

GRANT EXECUTE ON [ext].[DELETECONTOSORETAILTRANSACTIONPAYMENTTRANS] TO [DeployExtensibilityRole];
GO



