

create TABLE [ext].[RETAILSTORETENDERTYPETABLE](
	[CHANNEL] [bigint] NOT NULL,
	[TENDERTYPEID] [nvarchar](10) NOT NULL,
	[DATAAREAID] [nvarchar](4) NOT NULL,
	[DISPLAYORDER] [numeric](32, 6) NOT NULL default 0,
 CONSTRAINT [I_-1697922944_-828827534] PRIMARY KEY CLUSTERED 
(
	[CHANNEL] ASC,
	[TENDERTYPEID] ASC,
	[DATAAREAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


